using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BH.Builder.Components
{
    internal class Window
    {
        public static string getClosest(string key)
        {
            List<string> KeyWordList = new List<string>();
            foreach (WindowKeys val in Enum.GetValues(typeof(WindowKeys)))
            {
                KeyWordList.Add(val.ToString());
            }
            return APF.Find_Probabilities.GetClosest(key, KeyWordList.ToArray());
        }

        public static bool isHaveThisKey(string key)
        {
            foreach (WindowKeys val in Enum.GetValues(typeof(WindowKeys)))
            {
                if (val.ToString().Equals(key)) return true;
            }
            return false;
        }
    }

    public enum WindowKeys
    {
        ActualHeight,
        ActualWidth,
        AllowDrop,
        AllowsTransparency,
        AreAnyTouchesCaptured,
        AreAnyTouchesCapturedWithin,
        AreAnyTouchesDirectlyOver,
        AreAnyTouchesOver,
        Background,
        BindingGroup,
        BitmapEffect,
        BitmapEffectInput,
        BorderBrush,
        BorderThickness,
        CacheMode,
        Clip,
        ClipToBounds,
        CommandBindings,
        Content,
        ContentStringFormat,
        ContentTemplate,
        ContentTemplateSelector,
        ContextMenu,
        Cursor,
        DataContext,
        DefaultStyleKey,
        DependencyObjectType,
        DesiredSize,
        DialogResult,
        Dispatcher,
        Effect,
        FlowDirection,
        Focusable,
        FocusVisualStyle,
        FontFamily,
        FontSize,
        FontStretch,
        FontStyle,
        FontWeight,
        ForceCursor,
        Foreground,
        HandlesScrolling,
        HasAnimatedProperties,
        HasContent,
        HasEffectiveKeyboardFocus,
        Height,
        HorizontalAlignment,
        HorizontalContentAlignment,
        Icon,
        InheritanceBehavior,
        InputBindings,
        InputScope,
        IsActive,
        IsArrangeValid,
        IsEnabled,
        IsEnabledCore,
        IsFocused,
        IsHitTestVisible,
        IsInitialized,
        IsInputMethodEnabled,
        IsKeyboardFocused,
        IsKeyboardFocusWithin,
        IsLoaded,
        IsManipulationEnabled,
        IsMeasureValid,
        IsMouseCaptured,
        IsMouseCaptureWithin,
        IsMouseDirectlyOver,
        IsMouseOver,
        IsSealed,
        IsStylusCaptured,
        IsStylusCaptureWithin,
        IsStylusDirectlyOver,
        IsStylusOver,
        IsTabStop,
        IsVisible,
        Language,
        LayoutTransform,
        Left,
        LogicalChildren,
        Margin,
        MaxHeight,
        MaxWidth,
        MinHeight,
        MinWidth,
        Name,
        Opacity,
        OpacityMask,
        OverridesDefaultStyle,
        OwnedWindows,
        Owner,
        Padding,
        Parent,
        PersistId,
        RenderSize,
        RenderTransform,
        RenderTransformOrigin,
        ResizeMode,
        Resources,
        RestoreBounds,
        ShowActivated,
        ShowInTaskbar,
        SizeToContent,
        SnapsToDevicePixels,
        Style,
        StylusPlugIns,
        TabIndex,
        Tag,
        TaskbarItemInfo,
        Template,
        TemplatedParent,
        Title,
        ToolTip,
        Top,
        Topmost,
        TouchesCaptured,
        TouchesCapturedWithin,
        TouchesDirectlyOver,
        TouchesOver,
        Triggers,
        Uid,
        UseLayoutRounding,
        VerticalAlignment,
        VerticalContentAlignment,
        Visibility,
        VisualBitmapEffect,
        VisualBitmapEffectInput,
        VisualBitmapScalingMode,
        VisualCacheMode,
        VisualChildrenCount,
        VisualClearTypeHint,
        VisualClip,
        VisualEdgeMode,
        VisualEffect,
        VisualOffset,
        VisualOpacity,
        VisualOpacityMask,
        VisualParent,
        VisualScrollableAreaClip,
        VisualTextHintingMode,
        VisualTextRenderingMode,
        VisualTransform,
        VisualXSnappingGuidelines,
        VisualYSnappingGuidelines,
        Width,
        WindowStartupLocation,
        WindowState,
        WindowStyle
    }
}
